### PR TITLE
frame rate instead of animation duration

### PR DESCRIPTION
**Pull request by MondayHopscotch**
Specifying time per frame (frame rate) I think will be more usable so we don't have to do math to figure out how long an animation should be.

### CODE REVIEW

**Comment by Kenoshen** [comment]
Wouldn't time per frame cause you to have to do math to figure out how long an animation will be?  Maybe we can allow you to specify one or the other somehow.

**Comment by MondayHopscotch** [comment]
The math would be programmatic instead of us doing the math. 

With specifying total duration, we would have to do the math by hand when programming things (per animation since it depends on how many frames we put in it).

With specifying time/frame, we just pick a frame rate such as 1/24 (0.041f) and just pass that in for all animations.

**Comment by MondayHopscotch** [comment]
^ These are just my opinions, I didn't mean for them to come off as accusatory.

I was using this utility in the game I'm working on with Jake and Luke Fisher and was wanting a constant frame rate and was not enjoying having to count frames and do math. Both approaches will probably come up as something we'd want, so having a way to do things from either angle would be the most beneficial.

**Comment by Kenoshen** [comment]
Oh man, no worries. I'm not offended at all. You weren't being accusatory. This is good discussion. I can totally see what you are saying. I would guess that you are also right about both angles being valid in certain situations. My thought was for things like combos it would be easier to deal with the timing of each move if you were talking in terms of how long it took for the animation to complete. But on the other hand, for things like running, walking, or animation of static object like a river or a rustling bush, I could see the total time not really mattering and just giving a static per frame rate to everything to make it all consistent.

**Comment by Kenoshen** [comment]
The other thing I could put in there is which ever you first configure the animation with I will add 2 getters, one that returns the per frame time and the other that returns the total time. That way we can at least see either piece of info regardless of how it is initially set up.

**Comment by Kenoshen** [comment]
Just committed a change (8a7f4e8a) that uses a FrameRate object like:

FrameRate.total(1.0f);
or 
FrameRate.perFrame(0.16f);

On animation creation.  And you can get access to the total time or per frame time with:

float totalDur = animator.totalDuration();
float perFrameDur = animator.perFrameDuration();

I'm going to mark this PR as closed.

**Pull request closed without merging**
